from src.constants import *
import os,sys

ROOT_DIR = ROOT_DIR_KEY

#Data Ingestion

DATASET_PATH = os.path.join(ROOT_DIR,DATA_DIR,DATA_DIR_KEY)

RAW_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURRENT_TIME_STAMP,
                             DATA_INGESTION_RAW_DATA_DIR,RAW_DATA_DIR_KEY)

TRAIN_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURRENT_TIME_STAMP,
                               DATA_IMGESTION_INGESTED_DATA_DIR_KEY,TRAIN_DATA_DIR_KEY)

TEST_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_INGESTION_KEY,CURRENT_TIME_STAMP,
                               DATA_IMGESTION_INGESTED_DATA_DIR_KEY,TEST_DATA_DIR_KEY)


#Data Transformation


PREPROCESSING_OBJ_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,
                                      DATA_TRANSFORMATION_ARTIFACT,DATA_PREPROCESSED_DIR,DATA_TRANSFORMATION_PROCESSING_OBJ)

TRANSFORMED_TRAIN_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                        DATA_TRANSFORMATION_DIR,TRANSFORMATION_TRAIN_DIR_KEY)

TRANSFORMED_TEST_FILE_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_TRANSFORMATION_ARTIFACT,
                                        DATA_TRANSFORMATION_DIR,TRANSFORMATION_TEST_DIR_KEY)


FEATURE_ENG_OBJ_PATH = os.path.join(ROOT_DIR,ARTIFACT_DIR_KEY,DATA_PREPROCESSED_DIR,"feature_engg.pkl")


#Model training

MODEL_FILE_PATH = os.path.join(ROOT_DIR_KEY,ARTIFACT_DIR_KEY,MODEL_TRAINER_KEY,MODEL_OBJECT)
